### ISSUE TITLE
Correlated Events

### ISSUE THREAD

**Issue by farriesk** [PaloAltoNetworks/SplunkforPaloAltoNetworks#18]
The correlated events come in through the pan:log sourcetype but do not have the key fields extracted.

It would be great to have these fields extracted like they show up in the PA's Correlated Events screen.

match Time
Update Time
Object Name
Source Address
Source User
Severity
Summary
Match OID
Object ID

Would be great to see Destination Address as well if it becomes available.

**Comment by btorresgil** [comment]
Relates to pull request #23
