### ISSUE TITLE
GlobalProtect Logs

### ISSUE THREAD

**Issue by farriesk** [PaloAltoNetworks/SplunkforPaloAltoNetworks#19]
It would be great if you included a GlobalProtect dashboard.  I have built a few for myself but I'm sure the community would appreciate having one out of the box that they can either use or build upon.

**Comment by paulmnguyen** [comment]
We are currently working on a dashboard which is nearly complete. Do you mind sharing your current dashboard for GlobalProtect? I am interested in what kind of information your showing.

**Comment by farriesk** [comment]
Sure I can share it.  Which address should I send the images or do you want the source?



Kent Farries | Sr. Systems Analyst, Security Intelligence & Analytics
TRANSALTA CORPORATION
T: +1 (403) 267-7356 | C: +1 (403) 473-3402
Email<mailto:Kent_Farries@TransAlta.com> | Web<http://www.transalta.com/> | Facebook<http://www.facebook.com/TransAlta> | Twitter<http://www.twitter.com/TransAlta>

**Comment by paulmnguyen** [comment]
images are fine. panguyen@paloaltonetworks.com
