### ISSUE TITLE
Better Threat/Wildfire Dashboard user information

### ISSUE THREAD

**Issue by mattimustang** [PaloAltoNetworks/SplunkforPaloAltoNetworks#21]
I noticed that the wildfire dashboard was putting "unknown" for the user when the wildfire logs were for SMTP traffic and contained the email sender and recipient fields.

I've changed the `pan:threat` source so it captures the recipient or sender in the user field if src_user or dest_user are null as follows:

```
[pan:threat]
EVAL-user                           = coalesce(src_user,dest_user,recipient,sender,"unknown")
```

this makes the wildfire dashboard more accurate.

cheers

**Comment by btorresgil** [comment]
Added to Add-on 3.7.0
