### ISSUE TITLE
Search parser error

### ISSUE THREAD

**Issue by jdeer0618** [PaloAltoNetworks/SplunkforPaloAltoNetworks#24]
Splunk 6.4.0
App Version 5.2.0
Path - /en-US/app/SplunkforPaloAltoNetworks/threat_detail
Panel - Users by Kilobytes

When clicking the magnifying glass and opening the Users by Kilobytes panel there is a search parser error. This appears to be from an extra pipe (pictured below).

![screenshot_2](https://cloud.githubusercontent.com/assets/4651176/16825905/6ec3f130-493e-11e6-8d8a-5fbb70217e78.png)

**Comment by btorresgil** [comment]
Thank you for the issue submission.  We'll look into this.

**Comment by jdeer0618** [comment]
Found the issue. There is an extra pipe in the query.

![screenshot_1](https://cloud.githubusercontent.com/assets/4651176/16846041/91384d7a-49b0-11e6-94ec-d9c2648a6427.png)

**Comment by btorresgil** [comment]
Relates to pull request #26

**Comment by btorresgil** [comment]
Pull request #26 merged.  Closing this issue.
