### ISSUE TITLE
Backslashes not handled properly

### ISSUE THREAD

**Issue by jdeer0618** [PaloAltoNetworks/SplunkforPaloAltoNetworks#25]
Splunk 6.4.0
App Version 5.2.0
Path - /en-US/app/SplunkforPaloAltoNetworks/threat_detail

No data is shown when clicking through on the drill down for a user with the domain "\". This appears to be from the backslash not being escaped. The first pic shows no data when using a single slash and the second shows an escaped backslash.

![screenshot_3](https://cloud.githubusercontent.com/assets/4651176/16826060/d3d12f2e-493f-11e6-9ad1-4cdbaf9cc2af.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/4651176/16826105/16ca3208-4940-11e6-8868-50faa951ebbf.png)

**Comment by btorresgil** [comment]
Thanks again for submitting issues.  Looking into this one.

**Comment by btorresgil** [comment]
Relates to pull request #27
