### ISSUE TITLE
Tagging for events is incorrect

### ISSUE THREAD

**Issue by automine** [PaloAltoNetworks/SplunkforPaloAltoNetworks#29]
This is really more of an issue with the TA, but the tagging on the events is incorrect. The URL filtering items should go be tagged as "web" and "proxy". I would also suggest excluding the file identification events from the "ids" "attack" tags, as they create a ton of noise.

**Comment by btorresgil** [comment]
You're correct, the way the different log types are currently classified in CIM is not granular enough.  An improvement to this is almost ready for release and will be available in the next TA feature release.

**Comment by btorresgil** [comment]
Resolved by commit PaloAltoNetworks/Splunk_TA_paloalto@0732aabea1961294390484f3442cfbb2e34a6670
