### ISSUE TITLE
TA- pan_vendor_actions.csv change "blocked" to "dropped"

### ISSUE THREAD

**Issue by automine** [PaloAltoNetworks/SplunkforPaloAltoNetworks#30]
"dropped" is now a valid action, per CIM 4.5. As such the lookup for vendor_action to action should output and action of "dropped" when the vendor_action is "drop"

**Comment by btorresgil** [comment]
Thanks for the issue, you're correct it should be 'dropped'.  We'll change this in a future TA release.  Will update and close this issue when the change is released.

**Comment by btorresgil** [comment]
Added to Add-on 3.7.0
