### ISSUE TITLE
Splunk_TA_paloalto: Missing CIM field ids_type

### ISSUE THREAD

**Issue by hire-vladimir** [PaloAltoNetworks/SplunkforPaloAltoNetworks#31]
Per Network Traffic DM, *ids_type* field is required, the TA presently does not populate this. Suggested following enhancement to the TA:

props.conf
```
[pan:threat]
EVAL-ids_type = "network"
```

This field is primarily exposed within ES -> Intrusion Center -> "New Attacks - Last 30 Days" panel

**Comment by btorresgil** [comment]
Resolved for firewall in commit 4a5ddf39dff9fe0f52b93c205b48b3f0f8fdfb88
Resolved for endpoint in commit f7c8579f8f66d09b9d9bc83d0f6ac7831cfebf23
