### ISSUE TITLE
Issue with user filter for Threat Detail dashboard

### ISSUE THREAD

**Issue by paulmnguyen** [PaloAltoNetworks/SplunkforPaloAltoNetworks#42]
When clicking on a user from the Threat Overview dashboard no results are returned on the Threat Detail dashboard.

Issue is caused by escaping user with \ in it.

""log.user=\"tng\\crusher\"""

**Comment by mattimustang** [comment]
Hi Paul,

I think my PR #36 fixes this.

cheers

Matthew

**Comment by paulmnguyen** [comment]
Hi Matthew,

This was a different issue. To many double quotes.
I actually have a fix already for this however it will be release in our next version. Here are the instructions on how to fix the problem in the mean time before the release.

Go to the Threat Details Dashboard and click on “Edit” Top right corner.

Click on Source.

Go To Line 19 and 20
You will see this:
      <prefix>log.user="</prefix>
      <suffix>"</suffix>

Make it this:
       <prefix>log.user=</prefix>

we are removing the double quote from line 19 and removing line 20 completely.
