### ISSUE TITLE
Splunk 6.6.0 Support

### ISSUE THREAD

**Issue by farriesk** [PaloAltoNetworks/SplunkforPaloAltoNetworks#48]
We are looking for Splunk 6.6.0 support and would like to know when an upgraded version will be out to support this release.

Thank you

**Comment by paulmnguyen** [comment]
Hi Farriesk,

Thanks for the feedback regarding 6.6.0 support. I have tested the current release with Splunk 6.6.0 and it is compatible. I have updated Splunk Base to show support for 6.6.0.

Regards,

Paul Nguyen
