### ISSUE TITLE
Pan:Traffic & Network Traffic CIM

### ISSUE THREAD

**Issue by anthonygtellez** [PaloAltoNetworks/SplunkforPaloAltoNetworks#53]
pan:traffic does not match the CIM for Network Traffic:
http://docs.splunk.com/Documentation/CIM/4.8.0/User/NetworkTraffic

`protocol` expects OSI Layer3, not OSI Layer4. tcp/udp are `transport`
https://en.wikipedia.org/wiki/List_of_network_protocols_(OSI_model)#Layer_3_.28Network_Layer.29

add an eval to the TA to assume protocol is `ip` or include instructions to log this field from PA.

**Comment by btorresgil** [comment]
Hi @anthonygtellez, thanks for opening this issue.  Agreed, this should be `ip`, not `tcp`/`udp`.  We'll get this fixed in an upcoming release.

Thanks again!

**Comment by btorresgil** [comment]
Fixed in 6.0.0
