### ISSUE TITLE
Endpoint "Targeted Machines" panel should visualize `dest` field

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/SplunkforPaloAltoNetworks#55]
On the Endpoint Security dashboard the "Targeted Machines" panel shows the `src` field, but it should show the `dest` field.  `src` is the ESM while `dest` is the endpoint.

**Comment by paulmnguyen** [comment]
I reviewed my code and I am not using src ip. We are using device ip.

**Comment by btorresgil** [comment]
If you're looking on the newest dashboards, the panel is now called "Most Vulnerable Machines".  It's still using `src` which is the ESM, but it should use `dest` which is the targeted endpoint.  Just checked on App 5.4.0.

**Comment by btorresgil** [comment]
Added to App 5.4.1
