### ISSUE TITLE
Question on getting logs into Splunk

### ISSUE THREAD

**Issue by djbisbey** [PaloAltoNetworks/SplunkforPaloAltoNetworks#58]
PA version 8.0.1

Will not work with latest version of SplunkPA , docs say:

_In a single node environment, the latest Add-on (TA) is installed automatically by the App, and does not need to be installed separately. In clustered environments, the App and Add-on should be installed separately. Both can be installed by a deployment server._

but click on configure app says cannot find TA.

when I run eventtype="pan_config" I get No results found. Try expanding the time range. (all time).

I have ran wire-shark and syslog data is hitting machine.

I also manually installed the TA app but still does not work.

BizBo

**Comment by btorresgil** [comment]
Hello,

Make sure you install the TA and restart Splunk, add a data input for the port with sourcetype=pan:log, and configure the firewall to send config logs if you're looking for `eventtype="pan_config"`.

Thanks,
 -Brian

**Comment by btorresgil** [comment]
Is there anything else we can do to help you on this issue?  You can also find help at [Splunk Answers](https://answers.splunk.com/app/questions/491.html).

**Comment by btorresgil** [comment]
Closing issue, but please feel free to comment if you have further questions, or open a question on Splunk Answers
