### ISSUE TITLE
Parsing Issue

### ISSUE THREAD

**Issue by rbonfadini** [PaloAltoNetworks/SplunkforPaloAltoNetworks#71]
I have the 6.0.2 TA deployed per the instructions.  I'm receiving parsed logs for pan:threat, config, traffic, and system.  I'm still receiving pan:log, which I believe should be parsing out to pan:hipmatch. 
 What may be the issue where some, but not all sourcetypes are being parsed out correctly?

**Comment by btorresgil** [comment]
Hello, thanks for your question.  Can you send us a sample of the logs that have sourcetype `pan:log`?  A screenshot or raw export is fine.  You can redact it and post here, or send privately to splunkapp@paloaltonetworks.com.  Thanks!

**Comment by rbonfadini** [comment]
`Apr  4 22:23:52 panorama.domain 1,2018/04/04 22:23:52,002201003404,9479624,0x8000000000000000,HIPMATCH,0,508,2018/04/04 22:23:50,19,398,0,0,,firewall.hostname,1,domain\user,vsys1,hostname,8.8.8.8,HIP-PROFILE-RULE,1,Mac,profile,0,0,0.0.0.0`

**Comment by rbonfadini** [comment]
This was solved on our end.  The OOTB transforms.conf regex pattern for hipmatch wasn't lining up with our log output.
OOTB:
`[pan_hipmatch]
DEST_KEY = MetaData:Sourcetype
REGEX = ^[^,]+,[^,]+,[^,]+,HIPMATCH,
FORMAT = sourcetype::pan:hipmatch`

New:
`[pan_hipmatch]
DEST_KEY = MetaData:Sourcetype
REGEX = ^[^,]+,[^,]+,[^,]+,[^,]+,[^,]+,HIPMATCH,
FORMAT = sourcetype::pan:hipmatch`

**Comment by btorresgil** [comment]
For others visiting this page, the syslog format was changed in PAN-OS 8.0.5, but will be changed back.  If you are using an affected version of PAN-OS, workaround by creating this new file:

`$SPLUNK_HOME/etc/apps/Splunk_TA_paloalto/local/transforms.conf`
```
[pan_hipmatch]
DEST_KEY = MetaData:Sourcetype
REGEX = ^[^,]+,[^,]+,[^,]+,[^,]+,[^,]+,HIPMATCH
FORMAT = sourcetype::pan:hipmatch

[extract_hipmatch]
DELIMS = ","
FIELDS = "future_use1","receive_time","serial_number","sequence_number","action_flags","type","log_subtype","future_use2","generated_time","src_user","vsys","host_name","os","src_ip","hip_name","hip_count","hip_type","future_use3","future_use4","devicegroup_level1","devicegroup_level2","devicegroup_level3","devicegroup_level4","vsys_name","dvc_name","vsys_id","ipv6_system_address"
```
