### ISSUE TITLE
Release 6.1.0 has ep_node macro using data model named pan_endpoint

### ISSUE THREAD

**Issue by fkjensen** [PaloAltoNetworks/SplunkforPaloAltoNetworks#83]
I think the macro should be changed to use data model named pan_traps instead. 

As a workaround I created a local/macros.conf which contains

    [ep_node]
    definition = datamodel="pan_traps" WHERE nodename!="log.heartbeat"
    
    [ep_node(1)]
    args = nodename
    definition = datamodel="pan_traps" WHERE nodename="$nodename$"

That workaround will fix  https://localhost/en-US/app/SplunkforPaloAltoNetworks/data_model_audit which otherwise will complain about a missing data model named pan_endpoint.

**Comment by paulmnguyen** [comment]
This has been resolved in v6.1.1
