### ISSUE TITLE
retrieveNewApps.py broken?

### ISSUE THREAD

**Issue by idev** [PaloAltoNetworks/SplunkforPaloAltoNetworks#93]
Hello,

I notice that the retrieveNewApps.py script seems to be broken?
I guess the URL is no longer available?

python.log:

> 
> 2019-09-06 13:04:56,950 +0200 ERROR	common:239 -   File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/retrieveNewApps.py", line 133, in <module>
>     common.exit_with_error("Exception while getting new apps. Error: %s" % str(e))
>   File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/lib/common.py", line 239, in exit_with_error
>     logger.error(''.join(traceback.format_stack()))
> 2019-09-06 13:04:56,950 +0200 ERROR	common:241 - Exception while getting new apps. Error: <urlopen error [Errno 110] Connection timed out>
> 2019-09-06 13:04:59,254 +0200 ERROR	common:239 -   File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/retrieveNewApps.py", line 133, in <module>
>     common.exit_with_error("Exception while getting new apps. Error: %s" % str(e))
>   File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/lib/common.py", line 239, in exit_with_error
>     logger.error(''.join(traceback.format_stack()))
> 2019-09-06 13:04:59,255 +0200 ERROR	common:241 - Exception while getting new apps. Error: <urlopen error [Errno 110] Connection timed out>
> 2019-09-06 14:40:22,006 +0200 ERROR	common:239 -   File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/retrieveNewApps.py", line 133, in <module>
>     common.exit_with_error("Exception while getting new apps. Error: %s" % str(e))
>   File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/lib/common.py", line 239, in exit_with_error
>     logger.error(''.join(traceback.format_stack()))
> 2019-09-06 14:40:22,007 +0200 ERROR	common:241 - Exception while getting new apps. Error: <urlopen error [Errno 110] Connection timed out>

**Comment by paulmnguyen** [comment]
Removed in 6.2.0
